# Generated by Django 5.0.3 on 2026-03-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_alter_review_unique_together_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
