# Generated by Django 5.0.3 on 2026-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0025_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
