# Generated by Django 5.0.3 on 2026-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0027_remove_booking_products_remove_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
