# Generated by Django 5.0.3 on 2026-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0028_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
    ]
