# Generated by Django 5.0.3 on 2026-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0029_bookingitem_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
