# Generated by Django 5.0.3 on 2026-03-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0030_alter_bookingitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='product_desc',
            field=models.TextField(null=True),
        ),
    ]
