# Generated by Django 5.0.3 on 2026-03-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0033_alter_booking_payment_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, default='pending', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='grocery.payment'),
        ),
    ]
